### ISSUE TITLE
Negative NSUInteger in ThingSmartActivatorKit failing application build

### ISSUE THREAD

**Issue by foyst** [tuya/tuya-home-ios-sdk-sample-objc#9]
Hi,

I'm trying to use the new Thing (v5) SDK libraries used in this sample application in my own app. However when I do, the build in XCode fails saying that the `ThingSmartPerformanceGatewayPropertyErrorCode` enum in ThingSmartActivatorKit/Headers/ThingSmartPerformanceGatewayService.h (line 36) `Enumerator value evaluates to -10000, which cannot be narrowed to type 'NSUInteger' (aka 'unsigned long')`.

I'm not overly familiar with Objective-C, but my understanding is an unsigned integer cannot be a negative value, so I'm not sure how this is working in this sample project. I believe there's compiler flags you can use to ignore certain errors, but I've not found the difference in compiler flags between this project and my own.

If you could explain what I need to do in my project to get past this issue it'd be really appreciated!

**Comment by taojingGino** [comment]
@foyst could you show your Podfile.lock，we can check it.

**Comment by miyazaki2048** [comment]
The reason for this compilation issue is that the enumeration value of -10000 cannot be converted to the 'NSUInteger' type because the 'NSUInteger' type can only represent unsigned integers greater than or equal to zero. To solve this problem, you can try the following solutions:

1. Add the "-Wno-enum-conversion" flag to the compilation options. This flag tells the compiler to ignore warning messages about enumeration value conversion. However, this solution is not recommended because it may mask other potential issues and may cause unexpected errors in the application at runtime.

2.  We Will Change the 'NSUInteger' type to the 'NSInteger' type. The 'NSInteger' type can represent signed integers, including positive and negative numbers. We will release a fix version within 2 days, if you can wait.

**Comment by taojingGino** [comment]
@foyst Thank you for your feedback，we have already released ThingSmartActivatorKit 5.0.1 to fix this issue.

**Comment by foyst** [comment]
Thanks for getting back to me so quickly on this.

I upped to version 5.0.1, it looks like it's been fixed in one place but there's still 3 usages of `NSUInteger` from what I can see that's still causing errors:
```
ThingSmartPerformanceGatewayService.h:51
ThingSmartPerformanceGatewayService.h:63
ThingSmartPerformanceGateway.h:32
```
Thanks

**Comment by tobynnt** [comment]
> Thanks for getting back to me so quickly on this.
> 
> I upped to version 5.0.1, it looks like it's been fixed in one place but there's still 3 usages of `NSUInteger` from what I can see that's still causing errors:
> 
> ```
> ThingSmartPerformanceGatewayService.h:51
> ThingSmartPerformanceGatewayService.h:63
> ThingSmartPerformanceGateway.h:32
> ```
> 
> Thanks

Hi, I got the same issues. Have you solved it yet? 

Error: Enumerator value evaluates to -10000, which cannot be narrowed to type 'NSUInteger' (aka 'unsigned long')
/ThingSmartActivatorKit/ThingSmartActivatorKit.framework/Headers/ThingSmartPerformanceGateway.h:32:61 
/ThingSmartActivatorKit/ThingSmartActivatorKit.framework/Headers/ThingSmartPerformanceGatewayService.h:51:66
/ThingSmartActivatorKit/ThingSmartActivatorKit.framework/Headers/ThingSmartPerformanceGatewayService.h:63:68


<img width="1585" alt="Screenshot 2023-05-01 at 09 07 17" src="https://user-images.githubusercontent.com/130066197/235391799-ccead185-7eac-4002-bb25-2480bad52223.png">
